# Generated by Django 4.2.30 on 2026-05-24 18:07

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Username must contain only letters, numbers, and underscores.')])),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('LAB_ADMIN', 'Lab Admin'), ('TECHNICIAN', 'Technician'), ('CASHIER', 'Cashier'), ('COLLECTION_BOY', 'Collection Boy')], db_index=True, default='LAB_ADMIN', max_length=20)),
                ('status', models.CharField(db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('lab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, default='')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('admin_name', models.CharField(blank=True, default='', max_length=255)),
                ('admin_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tube_type', models.CharField(max_length=100)),
                ('tube_color', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lab', models.ForeignKey(db_column='lab_id', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='backend.lab')),
            ],
            options={
                'db_table': 'lab_tests',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MasterTest',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('tube_type', models.CharField(max_length=100)),
                ('tube_color', models.CharField(max_length=100)),
                ('default_price', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'master_tests',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='backend.lab')),
                ('logo_base64', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lab settings',
            },
        ),
        migrations.CreateModel(
            name='ReferredDoctor',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(db_index=True, max_length=255)),
                ('hospital_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_doctors', to='backend.lab')),
            ],
            options={
                'db_table': 'referred_doctors',
                'ordering': ['doctor_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientEntry',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('COLLECTED', 'Collected'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered')], db_index=True, default='CREATED', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('collected_by', models.CharField(blank=True, max_length=255, null=True)),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='backend.lab')),
                ('referred_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='backend.referreddoctor')),
                ('tests', models.ManyToManyField(related_name='patients', to='backend.labtest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MasterTestParameter',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('default_min', models.FloatField()),
                ('default_max', models.FloatField()),
                ('master_test', models.ForeignKey(db_column='master_test_id', on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='backend.mastertest')),
            ],
            options={
                'db_table': 'master_test_parameters',
            },
        ),
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('default_min', models.FloatField()),
                ('default_max', models.FloatField()),
                ('lab_test', models.ForeignKey(db_column='lab_test_id', on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='backend.labtest')),
            ],
            options={
                'db_table': 'lab_test_parameters',
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='master_test',
            field=models.ForeignKey(blank=True, db_column='master_test_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='backend.mastertest'),
        ),
        migrations.AddIndex(
            model_name='lab',
            index=models.Index(fields=['status', 'created_at'], name='backend_lab_status_68b6f0_idx'),
        ),
        migrations.AddField(
            model_name='expense',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='backend.lab'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.lab'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='referreddoctor',
            constraint=models.UniqueConstraint(fields=('lab', 'doctor_name', 'hospital_name'), name='unique_lab_doctor_hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='labtest',
            unique_together={('lab', 'code')},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['lab', 'role'], name='backend_cus_lab_id_2f308e_idx'),
        ),
    ]
