# Generated by Django 4.2.30 on 2026-05-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_expense_created_by_patiententry_concession_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requires_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
