# Generated by Django 4.2.30 on 2026-05-25 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_customuser_requires_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='patiententry',
            name='created_at',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
