# Generated by Django 4.2.30 on 2026-05-25 18:53

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_expense_date_alter_patiententry_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concession',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='activitylog',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='concession',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', backend.models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='expense',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lab',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='labtest',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='labtestparameter',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mastertest',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mastertestparameter',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='patiententry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='referreddoctor',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='report',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='activitylog',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concession',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='concession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concession',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='lab',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtest',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='labtest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mastertest',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='mastertest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastertest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mastertestparameter',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='mastertestparameter',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastertestparameter',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patiententry',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='patiententry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patiententry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referreddoctor',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='referreddoctor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referreddoctor',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='delete_flag',
            field=models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='report',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='concession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
