# Generated by Django 4.2.30 on 2026-05-25 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_concession_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiententry',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
