# Generated by Django 4.2.30 on 2026-05-25 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_patiententry_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists in this lab.'}, max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Username must contain only letters, numbers, and underscores.')]),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('lab', 'username', 'delete_flag'), name='unique_lab_username_delete_flag'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('lab__isnull', True)), fields=('username', 'delete_flag'), name='unique_global_username_delete_flag_when_no_lab'),
        ),
    ]
