# Generated by Django 4.2.30 on 2026-05-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_customuser_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
