# Generated by Django 4.2.30 on 2026-05-26 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_lab_lab_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiententry',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('COLLECTED', 'Collected'), ('LAB_RECEIVED', 'Received at Lab'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered')], db_index=True, default='CREATED', max_length=20),
        ),
        migrations.CreateModel(
            name='CashSettlement',
            fields=[
                ('delete_flag', models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_cash_expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_settlements', to=settings.AUTH_USER_MODEL)),
                ('collection_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boy_settlements', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='backend.lab')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('collection_boy', 'date')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
