# Generated by Django 4.2.30 on 2026-05-26 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_dailycloseout'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiententry',
            name='payment_status',
            field=models.CharField(choices=[('FULLY_PAID', 'Fully Paid'), ('PARTIAL_PENDING', 'Partial Pending'), ('FULL_CONCESSION', 'Full Concession'), ('CREDIT_PENDING', 'Credit Pending')], db_index=True, default='CREDIT_PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('delete_flag', models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('concession_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('CREDIT', 'Credit')], default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backend.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backend.patiententry')),
                ('received_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
