# Generated by Django 4.2.30 on 2026-05-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_paymenttransaction_collected_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='handed_over_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
