# Generated by Django 4.2.30 on 2026-05-27 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_paymenttransaction_handed_over_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='handed_over_date',
        ),
        migrations.AddField(
            model_name='cashsettlement',
            name='submitted_to_lab_admin',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='cashsettlement',
            name='submitted_to_lab_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitted_to_lab_admin',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitted_to_lab_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='submitted_to_lab_admin',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_index=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='submitted_to_lab_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CashierLabSettlement',
            fields=[
                ('delete_flag', models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenses_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cashier_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_lab_settlements', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_lab_settlements', to='backend.lab')),
            ],
            options={
                'db_table': 'cashier_lab_settlements',
                'ordering': ['-submitted_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='cashsettlement',
            name='cashier_lab_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_settlements', to='backend.cashierlabsettlement'),
        ),
        migrations.AddField(
            model_name='expense',
            name='cashier_lab_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='backend.cashierlabsettlement'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='cashier_lab_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='backend.cashierlabsettlement'),
        ),
    ]
