# Generated by Django 4.2.30 on 2026-05-29 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_paymenttransaction_handed_over_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierAdminSettlement',
            fields=[
                ('delete_flag', models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('gross_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(db_column='cashier_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_settlements', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(db_column='lab_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_settlements', to='backend.lab')),
            ],
            options={
                'db_table': 'cashier_admin_settlements',
                'ordering': ['-submitted_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CashierReceipt',
            fields=[
                ('delete_flag', models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('receipt_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(db_column='cashier_id', on_delete=django.db.models.deletion.CASCADE, related_name='cashier_receipts_handled', to=settings.AUTH_USER_MODEL)),
                ('cashier_admin_settlement', models.ForeignKey(blank=True, db_column='cashier_admin_settlement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='backend.cashieradminsettlement')),
                ('collection_boy', models.ForeignKey(db_column='collection_boy_id', on_delete=django.db.models.deletion.CASCADE, related_name='cashier_receipts_received', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cashier_receipts',
                'ordering': ['-receipt_date', '-receipt_time'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cashsettlement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cashsettlement',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='cashsettlement',
            name='cashier_lab_settlement',
        ),
        migrations.RemoveField(
            model_name='cashsettlement',
            name='collection_boy',
        ),
        migrations.RemoveField(
            model_name='cashsettlement',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='cashsettlement',
            name='lab',
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-transaction_date', '-transaction_time']},
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='handed_over_at',
            new_name='cashier_received_at',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='handed_over_to_cashier',
            new_name='submitted_to_cashier',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='received_date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='received_time',
            new_name='transaction_time',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='cashier_lab_settlement',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='cashier_lab_settlement',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='collected_by_user',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='handed_over_by_cashier',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='received_by_user',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='submitted_to_lab_admin',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='submitted_to_lab_admin_at',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='collection_boy',
            field=models.ForeignKey(blank=True, db_column='collection_boy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='lab',
            field=models.ForeignKey(db_column='lab_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backend.lab'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backend.patiententry'),
        ),
        migrations.AlterModelTable(
            name='paymenttransaction',
            table='payment_transactions',
        ),
        migrations.DeleteModel(
            name='CashierLabSettlement',
        ),
        migrations.DeleteModel(
            name='CashSettlement',
        ),
        migrations.AddField(
            model_name='expense',
            name='cashier_admin_settlement',
            field=models.ForeignKey(blank=True, db_column='cashier_admin_settlement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_expenses', to='backend.cashieradminsettlement'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='cashier_admin_settlement',
            field=models.ForeignKey(blank=True, db_column='cashier_admin_settlement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='backend.cashieradminsettlement'),
        ),
    ]
