# Generated by Django 4.2.30 on 2026-05-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_cashieradminsettlement_cashierreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cashier_receipt',
            field=models.ForeignKey(blank=True, db_column='cashier_receipt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_expenses', to='backend.cashierreceipt'),
        ),
    ]
