# Generated by Django 4.2.30 on 2026-05-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_expense_cashier_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='letterhead_base64',
            field=models.TextField(blank=True, help_text='Base64-encoded scanned letterhead image. Used as print background for each report page.', null=True),
        ),
    ]
