# Generated by Django 4.2.30 on 2026-06-03 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_add_letterhead_to_lab_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mastertest',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='DoctorCommissionEntry',
            fields=[
                ('delete_flag', models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='backend.referreddoctor')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='backend.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='backend.patiententry')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='backend.labtest')),
            ],
            options={
                'db_table': 'doctor_commission_entries',
                'ordering': ['-entry_date', '-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
