# Generated by Django 4.2.30 on 2026-06-04 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_labtest_commission_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.CharField(choices=[('Y', 'Deleted'), ('N', 'Active')], db_index=True, default='N', max_length=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('opening_cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cash_collected_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expenses_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cash_submitted_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('closing_cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_cash_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_cash_snapshot',
                'ordering': ['snapshot_date'],
                'unique_together': {('user', 'snapshot_date')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
