# Generated by Django 4.2.30 on 2026-06-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_dailycashsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['category', 'test_name']},
        ),
        migrations.RenameField(
            model_name='labtest',
            old_name='is_enabled',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='labtest',
            old_name='name',
            new_name='test_name',
        ),
        migrations.AddField(
            model_name='labtest',
            name='normal_range',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='labtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='tube_color',
            field=models.CharField(blank=True, default='Red', max_length=100),
        ),
        migrations.AlterModelTable(
            name='mastertest',
            table='master_test_library',
        ),
    ]
