# Generated by Django 4.2.30 on 2026-06-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_restore_customuser_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='pathologist_name',
            field=models.CharField(blank=True, default='Dr. Rajesh Sharma, MD', max_length=255),
        ),
    ]
